yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name="profile_unfollow"
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

urlpatterns += static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.csrf_failure'

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model
from posts.validators import validate_not_empty

User = get_user_model()


class Group(models.Model):
    title = models.CharField(
        max_length=200,
        verbose_name='Заголовок'
    )
    slug = models.SlugField(
        max_length=200,
        unique=True,
        verbose_name='ЧПУ',
    )
    description = models.TextField(
        max_length=400,
        verbose_name='Описание'
    )

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(verbose_name='Текст поста',
                            validators=[validate_not_empty],
                            help_text='Текст нового поста')
    pub_date = models.DateTimeField(
        verbose_name='Дата публикации',
        auto_now_add=True
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор',
        related_name='posts'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        related_name='posts',
        blank=True,
        null=True,
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    def __str__(self):
        return self.text[:15]

    class Meta:
        ordering = ['-pub_date']
        verbose_name_plural = 'Посты'
        verbose_name = 'Пост'


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Пост')
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор')
    text = models.TextField(
        verbose_name='Коментарий')
    created = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Создан')
    updated = models.DateTimeField(
        auto_now=True,
        verbose_name='Обнавлен')
    active = models.BooleanField(
        default=True,
        verbose_name='Активен')

    class Meta:
        ordering = ['-created']
        verbose_name_plural = 'Коментарии'
        verbose_name = 'Коментарий'

    def __str__(self):
        return self.text[:15]


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Пользователь')
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Автор')

    class Meta:
        verbose_name_plural = 'Подписки'
        verbose_name = 'Подписка'

    def __str__(self):
        return f'{self.user} подписался на {self.author}'

yatube/posts/forms.py
from django import forms

from django.utils.translation import gettext_lazy as _

from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        labels = {
            'text': _('Текст'),
            'group': _('Группа')
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

yatube/posts/views.py
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from django.shortcuts import render, get_object_or_404, redirect
from posts.models import Post, Group, Follow
from django.views.decorators.cache import cache_page

from posts.forms import CommentForm, PostForm
from django.conf import settings


User = get_user_model()


def paginate_queryset(posts, request):
    paginator = Paginator(posts, settings.POSTS)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return {
        'paginator': paginator,
        'page_number': page_number,
        'page_obj': page_obj
    }


@cache_page(20)
def index(request):
    posts = Post.objects.select_related('author', 'group')
    context = paginate_queryset(posts, request)
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.select_related('author')
    context = {
        'group': group,
        'posts': posts,
    }
    context.update(paginate_queryset(posts, request))
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    posts = author.posts.select_related('group')
    context = {
        'author': author,
        'posts': posts,
    }
    context.update(paginate_queryset(posts, request))
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    comments = post.comments.select_related('post')
    form = CommentForm()
    context = {
        'post': post,
        'requser': request.user,
        'comments': comments,
        'form': form,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def post_create(request):
    form = PostForm(
        request.POST or None,
        files=request.FILES or None)
    if form.is_valid():
        create_post = form.save(commit=False)
        create_post.author = request.user
        create_post.save()
        return redirect('posts:profile', create_post.author)
    context = {'form': form}
    return render(request, 'posts/post_create.html', context)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.user != post.author:
        return redirect('posts:post_detail', post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post)
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id)
    context = {'form': form, 'post': post, 'is_edit': True}
    return render(request, 'posts/post_create.html', context)


@login_required
def follow_index(request):
    posts = Post.objects.filter(
        author__following__user=request.user)
    paginator = Paginator(posts, settings.POSTS)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {'page_obj': page_obj}
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if author != request.user:
        Follow.objects.get_or_create(user=request.user, author=author)
    return redirect('posts:profile', author)


@login_required
def profile_unfollow(request, username):
    delete = get_object_or_404(
        Follow,
        user=request.user,
        author__username=username
    )
    delete.delete()
    return redirect('posts:profile', username)

yatube/templates/posts/follow.html
{% extends 'base.html' %} 
{% block title %}Подписки{% endblock %}
{% block content %}
{% include 'posts/includes/switcher.html' %}   
<div>  
  {% for post in page_obj %}
    {% include "includes/post_card.html" %}
  {% endfor %}   
  {% if page_obj.has_other_pages %}
    {% include "includes/paginator.html" %}
  {% endif %}
</div>
{% endblock  %} 

yatube/templates/posts/group_list.html
{% extends 'base.html' %} 
{% block title %} Записи сообщества {{ group }}{% endblock  %} 
{% block content %} 
  <div> 
    <h1>{{ group.title }}</h1> 
    <p>{{ group.description }}</p> 
    {% for post in page_obj %}
      {% include 'includes/post_card.html' %}
    {% endfor %}
    {% if page_obj.has_other_pages %}
      {% include 'includes/paginator.html' %}
    {% endif %}
  </div>
{% endblock  %}

yatube/templates/posts/index.html
{% extends 'base.html' %}  
{% block content %}
{% include 'posts/includes/switcher.html' %}
<div>
  <h1>Это главная страница проекта Yatube</h1>
  <h3>Последние обновления на сайте</h3>   
  {% for post in page_obj %}
    {% include "includes/post_card.html" %}
  {% endfor %}   
  {% if page_obj.has_other_pages %}
    {% include "includes/paginator.html" %}
  {% endif %}
</div>
{% endblock  %} 

yatube/templates/posts/post_create.html
{% extends "base.html" %}
{% block title %} {% if is_edit %} Редактировать запись {% else %} Добавить запись {% endif %} {% endblock %}
{% block content %}
{% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Создать статью
        </div>
        <div class="card-body">
          {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}            
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
          {% endif %}
          <form method="post" enctype="multipart/form-data"
          {% if is_edit %} 
              "{% url 'posts:post_edit' post.id %}" 
          {% else %}
              action="{% url 'posts:post_create' %}" 
          {% endif %} enctype="multipart/form-data">
          {% csrf_token %}
          {% for field in form %}
            <div class="form-group row my-3"
              {% if field.field.required %} 
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}
            >
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>
              <div>
              {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            </div>
          {% endfor %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary btn-block">{% if is_edit %}Сохранить{% else %}Добавить запись{% endif %}</button>
          </div>
          </form>
        </div>
      </div>
    </div>
</div> 
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load user_filters %}
{% load thumbnail %}
{% block title %}
  {{ post|truncatechars:30 }}
{% endblock title %}
{% block content %}
<div class="container py-5">
    <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ post.pub_date|date:'d E Y' }}
            </li>
              {% if post.group %}
              <li class="list-group-item">
                Группа: {{ post.group }}
                <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
              </li>
              {% endif %}
            <li class="list-group-item">
              Автор: {% if post.author.get_full_name %}{{ post.author.get_full_name }}{% else %}{{ post.author }}{% endif %}
            </li>
            <li class="list-group-item">
              Всего постов автора: {{ post.author.posts.count }}
            </li>
            <li class="list-group-item">
              <a href="{% url 'posts:profile' post.author %}">Все посты пользователя</a>
            </li>
          </ul>
        </aside>
        <article class="col-12 col-md-9">
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img-top" src="{{ im.url }}">
        {% endthumbnail %}
        <div class="card-body">
          <p class="card-text">
            {{ post.text }}
          </p>
            <a class="btn btn-primary" href="{% url 'posts:post_edit' post.pk %}">
              Редактировать запись
            </a>
        </div>
    {% if comments.count != 0 %}
    {% with comments.count as total_comments %}
    <hr>
    <figure>
      <blockquote class="blockquote">
        <div class="shadow-sm p-2 bg-white rounded">
          Комментариев {{ total_comments }}
        </div>
      </blockquote>
    </figure>
    {% endwith %}
    {% endif %}
    {% if user.is_authenticated %}
      <div class="card my-4">
        <h5 class="card-header">Добавить комментарий:</h5>
          <div class="card-body">
            <form method="post" action="{% url 'posts:add_comment' post.id %}">
              {% csrf_token %}      
              <div class="form-group mb-2">
                {{ form.text|addclass:"form-control" }}
              </div>
              <button type="submit" class="btn btn-primary">Отправить комментарий</button>
            </form>
          </div>
      </div>
    {% endif %}
    {% for comment in comments %}
      <div class="media mb-4">
        <div class="media-body">
          <div class="alert alert-primary" role="alert">
            {{ comment.created|date:'d E Y' }} <a href="{% url 'posts:profile' comment.author.username %}">{{ comment.author.get_full_name }}</a>:
          </div>
          <figure>
            <blockquote class="blockquote">
              <div class="shadow-sm p-3 bg-white">
                {{ comment.text|linebreaks }}
              </div>
            </blockquote>
          </figure>
        </div>
      </div>
    {% empty %}
    <hr>
    <figure>
      <blockquote class="blockquote">
        <div class="shadow-sm p-2 bg-white rounded">
          Комментариев пока нет! 
        </div>
      </blockquote>
    </figure>
    {% endfor %}
  </article>
</div>
{% endblock content %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %} Профайл пользователя {{ author }}{% endblock title %}
{% block content %}
<div class="card bg-light" style="width: 100%">
    <div class="card-body">
        <h1 class="card-title">Все посты пользователя {% if author.get_full_name %}{{ author.get_full_name }}{% else %}{{ author }}{% endif %}</h1>
        <h3 class="card-text">Всего постов: {{ page_obj.paginator.count }}</h3>
        {% if request.user != author %}
            {% if following %}
                <a
                class="btn btn-lg btn-light"
                href="{% url 'posts:profile_unfollow' author.username %}" role="button"
                >
                Отписаться
                </a>
                {% else %}
                <a
                    class="btn btn-lg btn-primary"
                    href="{% url 'posts:profile_follow' author.username %}" role="button"
                >
                Подписаться
                </a>
            {% endif %}
        {% endif %}
    </div>
</div>
    {% for post in page_obj %}
        {% include "includes/post_card.html" %}
    {% endfor %}
    {% if page_obj.has_other_pages %}
        {% include "includes/paginator.html" %}
    {% endif %}
</div>
{% endblock content %}